#!/usr/bin/env python3
"""Build a compact dev10 quantization metrics table.

The script expects each run directory to contain:
  - eval.json
  - qwen_runtime_calls.csv, generated by tools/summarize_qwen_runtime.py
  - optionally run_metadata.json, written by run_qwen_dev10_quant_suite.sh

It writes:
  <output-prefix>.csv
  <output-prefix>.md
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import statistics
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional


DEFAULT_RUN_ORDER = [
    "raw_transformers",
    "lora_transformers",
    "gptq_w4a16_vllm",
    "bf16_transformers",
    "bf16_vllm",
    "w8a8_int8_vllm",
    "awq_w4a16_n64_vllm",
    "gptq_w4a16_n64_vllm",
    "mixed_gptq_w4w8a16_vllm",
    "actaware_mixed_gptq_w4w8a16_vllm",
    "awq_scaled_gptq_w4a16_vllm",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--suite-root",
        required=True,
        help="Directory containing one subdirectory per quantization run.",
    )
    parser.add_argument(
        "--output-prefix",
        default="",
        help="Output prefix. Default: <suite-root>/qwen_dev10_quant_metrics",
    )
    return parser.parse_args()


def as_float(value: Any) -> Optional[float]:
    try:
        x = float(value)
    except (TypeError, ValueError):
        return None
    return x if math.isfinite(x) else None


def percentile(values: List[float], pct: float) -> Optional[float]:
    if not values:
        return None
    xs = sorted(values)
    if len(xs) == 1:
        return xs[0]
    rank = (len(xs) - 1) * pct / 100.0
    lo = int(math.floor(rank))
    hi = int(math.ceil(rank))
    if lo == hi:
        return xs[lo]
    return xs[lo] * (hi - rank) + xs[hi] * (rank - lo)


def read_json(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError:
        return {}


def route_records(eval_data: Dict[str, Any]) -> List[Dict[str, Any]]:
    checkpoint = eval_data.get("_checkpoint") or {}
    records = checkpoint.get("records") or []
    return [r for r in records if isinstance(r, dict)]


def global_record(eval_data: Dict[str, Any]) -> Dict[str, Any]:
    checkpoint = eval_data.get("_checkpoint") or {}
    record = checkpoint.get("global_record") or {}
    return record if isinstance(record, dict) else {}


def is_full_score(record: Dict[str, Any]) -> bool:
    scores = record.get("scores") or {}
    return (
        nearly(scores.get("score_composed"), 100.0)
        and nearly(scores.get("score_route"), 100.0)
        and nearly(scores.get("score_penalty"), 1.0)
    )


def nearly(value: Any, target: float, eps: float = 1e-6) -> bool:
    x = as_float(value)
    return x is not None and abs(x - target) <= eps


def count_infractions(records: Iterable[Dict[str, Any]], key: str) -> int:
    count = 0
    for record in records:
        infractions = record.get("infractions") or {}
        values = infractions.get(key) or []
        if isinstance(values, list):
            count += len(values)
    return count


def csv_rows(path: Path) -> List[Dict[str, str]]:
    if not path.exists():
        return []
    with path.open(newline="") as f:
        return list(csv.DictReader(f))


def runtime_metrics(run_dir: Path) -> Dict[str, Any]:
    rows = csv_rows(run_dir / "qwen_runtime_calls.csv")
    e2e = [x for x in (as_float(r.get("end_to_end_latency_s")) for r in rows) if x is not None]
    gen = [x for x in (as_float(r.get("generation_latency_s")) for r in rows) if x is not None]
    tps = [x for x in (as_float(r.get("tokens_per_s")) for r in rows) if x is not None]
    peak = [x for x in (as_float(r.get("cuda_max_allocated_gib")) for r in rows) if x is not None]
    load_delta = [
        x for x in (as_float(r.get("load_memory_delta_allocated_gib")) for r in rows) if x is not None
    ]
    gen_peak_delta = [
        x
        for x in (as_float(r.get("generation_peak_delta_allocated_gib")) for r in rows)
        if x is not None
    ]

    paper_peak = paper_value(run_dir / "qwen_runtime_paper_table.csv", "Peak Memory(GB) ↓")
    paper_model_size = paper_value(run_dir / "qwen_runtime_paper_table.csv", "Model Size(GB) ↓")

    if paper_peak is not None:
        peak_memory = paper_peak
    elif load_delta and gen_peak_delta:
        peak_memory = max(load_delta) + max(gen_peak_delta)
    elif peak:
        peak_memory = max(peak)
    else:
        peak_memory = None

    total_e2e = sum(e2e)
    return {
        "calls": len(rows),
        "avg_latency_ms": statistics.mean(e2e) * 1000.0 if e2e else None,
        "p95_latency_ms": percentile(e2e, 95) * 1000.0 if e2e else None,
        "avg_generation_ms": statistics.mean(gen) * 1000.0 if gen else None,
        "vlm_inference_fps": len(e2e) / total_e2e if total_e2e > 0 else None,
        "tokens_per_s": statistics.mean(tps) if tps else None,
        "gpu_peak_memory_gb": peak_memory,
        "model_size_gb": paper_model_size,
    }


def paper_value(path: Path, key: str) -> Optional[float]:
    rows = csv_rows(path)
    if not rows:
        return None
    return as_float(rows[0].get(key))


def eval_metrics(run_dir: Path) -> Dict[str, Any]:
    data = read_json(run_dir / "eval.json")
    records = route_records(data)
    global_rec = global_record(data)
    scores = global_rec.get("scores_mean") or {}
    meta = global_rec.get("meta") or {}

    route_count = len(records)
    success_100 = sum(1 for r in records if is_full_score(r))
    duration_game = as_float(meta.get("duration_game"))
    duration_system = as_float(meta.get("duration_system"))
    runtime_ratio = (
        duration_game / duration_system
        if duration_game is not None and duration_system and duration_system > 0
        else None
    )

    return {
        "routes": route_count,
        "driving_score": as_float(scores.get("score_composed")),
        "route_completion": as_float(scores.get("score_route")),
        "infraction_penalty": as_float(scores.get("score_penalty")),
        "success_100_routes": success_100,
        "success_100_rate_pct": (100.0 * success_100 / route_count) if route_count else None,
        "collisions": (
            count_infractions(records, "collisions_pedestrian")
            + count_infractions(records, "collisions_vehicle")
            + count_infractions(records, "collisions_layout")
        ),
        "red_light": count_infractions(records, "red_light"),
        "stop_infraction": count_infractions(records, "stop_infraction"),
        "route_timeout": count_infractions(records, "route_timeout"),
        "agent_blocked": count_infractions(records, "vehicle_blocked"),
        "min_speed_infractions": count_infractions(records, "min_speed_infractions"),
        "duration_game_s": duration_game,
        "duration_system_s": duration_system,
        "runtime_ratio": runtime_ratio,
        "effective_sim_fps": 20.0 * runtime_ratio if runtime_ratio is not None else None,
    }


def run_dirs(suite_root: Path) -> List[Path]:
    dirs = [p for p in suite_root.iterdir() if p.is_dir() and (p / "eval.json").exists()]

    def key(path: Path) -> tuple[int, str]:
        metadata = read_json(path / "run_metadata.json")
        run_id = metadata.get("run_id", path.name)
        try:
            idx = DEFAULT_RUN_ORDER.index(run_id)
        except ValueError:
            idx = len(DEFAULT_RUN_ORDER)
        return idx, path.name

    return sorted(dirs, key=key)


def build_rows(suite_root: Path) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    for run_dir in run_dirs(suite_root):
        metadata = read_json(run_dir / "run_metadata.json")
        run_id = metadata.get("run_id", run_dir.name)
        row: Dict[str, Any] = {
            "run_id": run_id,
            "model": metadata.get("model_label", "Qwen3-VL-8B"),
            "quant": metadata.get("quant_label", run_dir.name),
            "backend": metadata.get("backend", ""),
            "out_dir": str(run_dir),
        }
        row.update(eval_metrics(run_dir))
        row.update(runtime_metrics(run_dir))
        rows.append(row)
    return rows


def fmt(value: Any, digits: int = 3) -> str:
    if value is None:
        return ""
    x = as_float(value)
    if x is None:
        return str(value)
    return f"{x:.{digits}f}"


def write_csv(path: Path, rows: List[Dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames: List[str] = []
    for row in rows:
        for key in row:
            if key not in fieldnames:
                fieldnames.append(key)
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_markdown(path: Path, rows: List[Dict[str, Any]]) -> None:
    columns = [
        ("Model", "model", 0),
        ("Quant", "quant", 0),
        ("DS ↑", "driving_score", 2),
        ("RC ↑", "route_completion", 2),
        ("Success@100 ↑", "success_100_rate_pct", 1),
        ("Avg Latency(ms) ↓", "avg_latency_ms", 2),
        ("P95 Latency(ms) ↓", "p95_latency_ms", 2),
        ("VLM FPS ↑", "vlm_inference_fps", 3),
        ("GPU Memory ↓", "gpu_peak_memory_gb", 3),
        ("Model Size(GB) ↓", "model_size_gb", 3),
        ("Calls", "calls", 0),
    ]
    lines = []
    lines.append("| " + " | ".join(name for name, _, _ in columns) + " |")
    lines.append("| " + " | ".join("---" for _ in columns) + " |")
    for row in rows:
        cells = []
        for _, key, digits in columns:
            value = row.get(key)
            cells.append(fmt(value, digits) if isinstance(value, (int, float)) or value is None else str(value))
        lines.append("| " + " | ".join(cells) + " |")
    path.write_text("\n".join(lines) + "\n")


def main() -> None:
    args = parse_args()
    suite_root = Path(args.suite_root)
    prefix = Path(args.output_prefix) if args.output_prefix else suite_root / "qwen_dev10_quant_metrics"
    rows = build_rows(suite_root)
    write_csv(Path(str(prefix) + ".csv"), rows)
    write_markdown(Path(str(prefix) + ".md"), rows)
    print(f"csv: {prefix}.csv")
    print(f"md:  {prefix}.md")


if __name__ == "__main__":
    main()
